theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  
title: EnzoBnl's notes

description: >-
    <a href="http://enzobnl.github.io" style="color: #f2f2f2">HOME</a> × <a href="notes.html" style="color: #f2f2f2">Day notes</a> × <a href="works.html" style="color: #f2f2f2">Works</a> × <a href="http://linkedin.com/in/enzo-bonnal" style="color: #f2f2f2">LinkedIn</a>
    
github:
  repository_url: https://github.com/enzobnl
