theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  
title: <a href="http://enzobnl.github.io"> enzobnl's notes</a>

description: <a href="notes.html">NOTES</a> <a href="cv.html">CV</a> <link rel="icon" type="image/png" href="./imgs/favicon_db.png" /><script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js"></script><script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {skipTags: ['script', 'noscript','style', 'textarea', 'pre'],inlineMath: [['$','$']]}});</script><script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script><script>document.body.style.background = "#ffffff";</script>
