theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  
title: enzobnl's notes

description: >-
    <a href="http://enzobnl.github.io" style="color: #f2f2f2">HOME</a> <a href="notes.html" style="color: #f2f2f2">NOTES</a> <a href="cv.html" style="color: #f2f2f2">CV</a>

