theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  
title: Enzo Bonnal's

description: >-
    <a href="index.html" style="color: #f2f2f2">Works</a> × <a href="notes.html" style="color: #f2f2f2">Notes</a> × <a href="http://linkedin.com/in/enzo-bonnal" style="color: #f2f2f2">LinkedIn</a>
    
github:
  repository_url: https://github.com/enzobnl
