theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  
title: Enzo Bonnal's

description: >-
    <a href="index.html" style="color: #f2f2f2">Works</a> × <a href="notes.html" style="color: #f2f2f2">Notes</a> × <a href="http://linkedin.com/in/enzo-bonnal" style="color: #f2f2f2">LinkedIn</a> × <a href="https://stackoverflow.com/users/6580080/enzobnl?tab=answers&sort=newest#user-tab-answers" style="color: #f2f2f2"><img src="https://cdn.sstatic.net/Sites/stackoverflow/company/img/logos/so/so-icon.svg?v=f13ebeedfa9e" width="100"></img>StackOverflow</a> × <a href="https://github.com/enzobnl" style="color: #f2f2f2">Github</a>
    
github:
  repository_url: https://github.com/enzobnl
