theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  
title: >-
    <a href="/" style="color: #f2f2f2">Home</a>

description: >-
    <a href="works.html" style="color: #f2f2f2">Works</a> × <a href="notes.html" style="color: #f2f2f2">Notes</a> × <a href="http://linkedin.com/in/enzo-bonnal" style="color: #f2f2f2">LinkedIn</a> × <a href="https://stackoverflow.com/users/6580080/bonnal-enzo?tab=answers&sort=newest#user-tab-answers" style="color: #f2f2f2">StackOverflow</a> × <a href="https://github.com/bonnal-enzo" style="color: #f2f2f2">Github</a>
    
github:
  repository_url: https://github.com/bonnal-enzo
